AlexaHomePage:
    desc: alexa主页
    locators:
        - name: Skills
          by: xpath
          value: //*[@id="iApps"]

        - name: YourSkills
          by:  xpath
          value: //*[text()='Your Skills']

