SearchPage:
    desc: 搜索
    locators:

        - name: 百度搜索框
          by: id
          value: kw

        - name: 百度一下按钮
          by: xpath
          value: //*[@id="su"]

        - name: 百度一下
          by: class
          value: bg s_btn

        - name: 第一条结果
          by: xpath
          value: //*[@id="1"]/h3
