username:
   alexa_cy: yukincao@etekcity.com.cn
   alexa_nana: kgdnn999@gmail.com
   vesync_cy: yukincao@etekcity.com.cn

password:
   alexa_cy: 1234567
   alexa_nana: 123456
   vesync_cy: 123456

keyWord:
  input: python